services:
  notes.api:
    image: ${DOCKER_REGISTRY-}notesapi
    container_name: notes.api
    build:
      context: .
      dockerfile: Notes.API\Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://notes.dashboard:18889
    networks:
      - otel

  notes.dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:latest 
    container_name: notes.dashboard
    ports:
      - 18888:18888
    networks:
      - otel

  notes.database:
    image: postgres:latest
    container_name: notes.database
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://notes.dashboard:18889
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=NotesDb
    volumes:
      - ./.containers/notes-db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - otel      

networks:
    otel: